### ISSUE TITLE
@Installation Docker Mac - '/' instead of '\'

### ISSUE THREAD

**Issue by jan-eberwein** [Digital-Media/fhooe-web-dock#1]
when running "docker compose -f .\docker-compose.fhooe.yml up -d" on macOS you need '/' instead of '\'
so the valid command would be "docker compose -f ./docker-compose.fhooe.yml up -d"

**Comment by martinharrer** [comment]
INSTALL.md was updated. issue fixed with commit  4b8dd61cf3eccaf2f0837ebe1e5b5b9f813a2823
